### ISSUE TITLE
panic while removing a running pod

### ISSUE THREAD

**Issue by carmark** [hyperhq/hyper#119]
I encountered the following panic when I remove a running pod.

```
[HYPER INFO  1029 16:11:31 10750 init_comm.go] [:47] console output end
[HYPER ERROR 1029 16:11:31 10750 tty.go] [:75] read tty data failed
[HYPER INFO  1029 16:11:31 10750 tty.go] [:136] tty socket closed, quit the reading goroutine EOF
[HYPER INFO  1029 16:11:31 10750 tty.go] [:103] tty chan closed, quit sent goroutine
[HYPER ERROR 1029 16:11:31 10750 init_comm.go] [:76] read init data failed
[HYPER INFO  1029 16:11:31 10750 volume_linux.go] [:43] Ready to unmount the target : /var/run/hyper/vm-McPowSZcIl/share_dir/28ac8b43689966f059eaec6620c91f8aa7139bed2cc9b270eb609fe851934b56/rootfs
[HYPER INFO  1029 16:11:31 10750 hypervisor.go] [:29] main event loop got message 36(ERROR_INTERRUPTED)
[HYPER INFO  1029 16:11:31 10750 vm_states.go] [:680] Connection interrupted while destroying
[HYPER INFO  1029 16:11:31 10750 hypervisor.go] [:29] main event loop got message 36(ERROR_INTERRUPTED)
[HYPER INFO  1029 16:11:31 10750 vm_states.go] [:680] Connection interrupted while destroying
[HYPER INFO  1029 16:11:31 10750 hypervisor.go] [:29] main event loop got message 7(EVENT_CONTAINER_DELETE)
[HYPER INFO  1029 16:11:31 10750 devicemap.go] [:370] container 0 umounted
[HYPER INFO  1029 16:11:31 10750 vm_states.go] [:309] Unplug container return with true
[HYPER INFO  1029 16:11:31 10750 devicemap.go] [:90] All resource being released, someone is waiting for us...
[HYPER INFO  1029 16:11:31 10750 context.go] [:243] no more device to release/remove/umount, quit
[HYPER INFO  1029 16:11:31 10750 qemu_process.go] [:21] quit watch dog.
[HYPER INFO  1029 16:11:31 10750 daemon.go] [:500] success to delete the VM info for pod(pod-IlRWIDcHLE)
[HYPER INFO  1029 16:11:31 10750 rm.go] [:80] Ready to rm container: 28ac8b43689966f059eaec6620c91f8aa7139bed2cc9b270eb609fe851934b56
[HYPER INFO  1029 16:11:31 10750 asm_amd64.s] [:438] unlock PodList
[HYPER INFO  1029 16:11:31 10750 job.go] [:84] -job podRm(pod-IlRWIDcHLE) OK
2015/10/29 16:11:31 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc8201aa6e0, 0x7ff194ae2998, 0xc82021a138)
	/usr/local/go/src/net/http/server.go:1220 +0xb5
github.com/tchap/go-patricia/patricia.(*Trie).Delete(0xc820148640, 0xc820437480, 0x40, 0x40, 0x40)
	/home/lei/src/github.com/hyperhq/hyper/Godeps/_workspace/src/github.com/tchap/go-patricia/patricia/patricia.go:266 +0x1c8
github.com/hyperhq/hyper/lib/docker/pkg/truncindex.(*TruncIndex).Delete(0xc82014c8a0, 0xc8203f28c0, 0x40, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/lib/docker/pkg/truncindex/truncindex.go:76 +0x195
github.com/hyperhq/hyper/lib/docker/daemon.(*Daemon).rm(0xc8201aa8f0, 0xc8203f8180, 0x1, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/lib/docker/daemon/delete.go:124 +0x10e5
github.com/hyperhq/hyper/lib/docker/daemon.(*Daemon).ContainerRm(0xc8201aa8f0, 0xc8204361c0, 0x40, 0xc82029913d, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/lib/docker/daemon/delete.go:48 +0x4f6
github.com/hyperhq/hyper/docker.(*Docker).SendCmdDelete(0xc82021a1c8, 0xc820418160, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/docker/delete.go:18 +0xbf
github.com/hyperhq/hyper/daemon.(*Daemon).CleanPod(0xc8201624b0, 0xc82048075e, 0xe, 0xcd3f00, 0x0, 0x0, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/daemon/rm.go:81 +0xc04
github.com/hyperhq/hyper/daemon.(*Daemon).CmdPodRm(0xc8201624b0, 0xc8204202d0, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/daemon/rm.go:25 +0x1de
github.com/hyperhq/hyper/daemon.(*Daemon).CmdPodRm-fm(0xc8204202d0, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/daemon/daemon.go:86 +0x38
github.com/hyperhq/hyper/engine.(*Job).Run(0xc8204202d0, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/engine/job.go:95 +0x6b2
github.com/hyperhq/hyper/server.postPodRemove(0xc8200b0540, 0xc820480747, 0x5, 0x7ff19996d470, 0xc820260370, 0xc8203ca0e0, 0xc820473aa0, 0x0, 0x0)
	/home/lei/src/github.com/hyperhq/hyper/server/server.go:874 +0x3da
github.com/hyperhq/hyper/server.makeHttpHandler.func1(0x7ff19996d470, 0xc820260370, 0xc8203ca0e0)
	/home/lei/src/github.com/hyperhq/hyper/server/server.go:1059 +0xa84
net/http.HandlerFunc.ServeHTTP(0xc8202f2de0, 0x7ff19996d470, 0xc820260370, 0xc8203ca0e0)
	/usr/local/go/src/net/http/server.go:1355 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820254190, 0x7ff19996d470, 0xc820260370, 0xc8203ca0e0)
	/home/lei/src/github.com/hyperhq/hyper/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.serverHandler.ServeHTTP(0xc8203bcf00, 0x7ff19996d470, 0xc820260370, 0xc8203ca0e0)
	/usr/local/go/src/net/http/server.go:1795 +0x19e
net/http.(*conn).serve(0xc8201aa6e0)
	/usr/local/go/src/net/http/server.go:1294 +0xbea
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1843 +0x3f6
```

**Comment by carmark** [comment]
this issue will be fixed by https://github.com/hyperhq/hyper/pull/121
