### ISSUE TITLE
hyperd daemon crash when qemu not started

### ISSUE THREAD

**Issue by hustcat** [hyperhq/hyper#13]
```
[HYPER INFO  0603 18:43:02 04546 server.go] Calling POST /pod/run
[HYPER INFO  0603 18:43:02 04546 job.go] +job podRun({"id":"ubuntu:14.04-7631605141","containers":[{"name":"ubuntu:14.04-7631605141","image":"ubuntu:14.04","command":["/bin/sh"],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""})
[HYPER INFO  0603 18:43:02 04546 pod.go] {"id":"ubuntu:14.04-7631605141","containers":[{"name":"ubuntu:14.04-7631605141","image":"ubuntu:14.04","command":["/bin/sh"],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""}
[HYPER ERROR 0603 18:43:02 04546 vm_states.go] Qemu did not start up properly, go to cleaning up
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x561b46]

goroutine 59 [running]:
runtime.panic(0x8b13a0, 0xbd7dd3)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
hyper/qemu.func·012(0x0, 0x0)
        /data/go/src/hyper/qemu/qmp_handler.go:335 +0x86
hyper/qemu.qmpHandler(0xc2085c4120)
        /data/go/src/hyper/qemu/qmp_handler.go:374 +0x2be
created by hyper/qemu.QemuLoop
        /data/go/src/hyper/qemu/qemu.go:45 +0x13a
```

Base CentOS7.

**Comment by gnawux** [comment]
Hi @hustcat , looks there is a bug in fail processing routine. 

As you are under CentOS 7, could you just try `which qemu-system-x86_64`. if it is not listed in your ${PATH}, add the qemu bin PATH (such as `/usr/local/bin`) into PATH.

Sorry for the panic.

**Comment by gnawux** [comment]
no further progress in this issue, will close this.

@hustcat hyper has many new commits and release since this issue was create, if you find any more problems, you can reopen this or create a new one.
