### ISSUE TITLE
pod create failed with files configured

### ISSUE THREAD

**Issue by gao-feng** [hyperhq/hyper#54]
```
[HYPER INFO  0825 17:39:55 26321 pod.go] [:162] Process the Containers section in POD SPEC
[HYPER INFO  0825 17:39:55 26321 tags.go] [:133] LookupImage Name is ubuntu:latest
[HYPER INFO  0825 17:39:56 26321 pod.go] [:518] The config: kernel=/home/gaofeng/git/hyperStart/build/kernel, initrd=/home/gaofeng/git/hyperStart/build/hyper-initrd.img
POD id is pod-jUOJEOaYkd
[HYPER INFO  0825 17:39:56 26321 container.go] [:10] ready to get the container(f5ea1ec52db1ee30af4f5d8225ba5c6c05a99f14d67ec3d18ec6993ebe46832f) info
[HYPER INFO  0825 17:39:56 26321 job.go] [:84] -job podRun({
	"id": "test-ubuntu-interface",
	"containers" : [{
	    "name": "ubuntu-interface",
	    "image": "ubuntu:latest",
	    "workdir": "/",
	    "command": ["/bin/bash"],
	    "files": [{
		"filename": "dns",
		"path": "/etc/resolv.conf",
		"perm": "0755"
	    }]
	}],
	"resource": {
	    "vcpu": 1,
	    "memory": 512
	},
	"files": [{
	    "name": "dns",
	    "encoding": "raw",
	    "content": "nameserver: 114.114.114.114"
	}],
	"volumes": [],
	"tty": true
}
, no) OK
2015/08/25 17:39:56 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 129 [running]:
net/http.func·011()
	/usr/lib/golang/src/net/http/server.go:1130 +0xbb
github.com/hyperhq/hyper/daemon.(*Daemon).ParsePod(0xc2085ca1c0, 0xc2082410e0, 0xc20807c840, 0xc208374710, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/daemon/pod.go:337 +0x52c6
github.com/hyperhq/hyper/daemon.(*Daemon).StartPod(0xc2085ca1c0, 0xc208379570, 0xe, 0xc2080bbc20, 0x1cc, 0x0, 0x0, 0x0, 0x0, 0x410000, ...)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/daemon/pod.go:572 +0xa2f
github.com/hyperhq/hyper/daemon.(*Daemon).CmdPodRun(0xc2085ca1c0, 0xc2082925a0, 0x0, 0x0)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/daemon/pod.go:102 +0x44b
github.com/hyperhq/hyper/daemon.*Daemon.CmdPodRun·fm(0xc2082925a0, 0x0, 0x0)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/daemon/daemon.go:88 +0x43
github.com/hyperhq/hyper/engine.(*Job).Run(0xc2082925a0, 0x0, 0x0)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/engine/job.go:95 +0x743
github.com/hyperhq/hyper/server.postPodRun(0xc2080be0e0, 0xc20825ce07, 0x5, 0x7f621c435998, 0xc208240dc0, 0xc20824c680, 0xc20830ac00, 0x0, 0x0)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/server/server.go:558 +0x337
github.com/hyperhq/hyper/server.func·001(0x7f621c435998, 0xc208240dc0, 0xc20824c680)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/server/server.go:883 +0x99d
net/http.HandlerFunc.ServeHTTP(0xc20821c540, 0x7f621c435998, 0xc208240dc0, 0xc20824c680)
	/usr/lib/golang/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20818d220, 0x7f621c435998, 0xc208240dc0, 0xc20824c680)
	/home/gaofeng/go/src/github.com/hyperhq/hyper/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2082292c0, 0x7f621c435998, 0xc208240dc0, 0xc20824c680)
	/usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208240c80)
	/usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:1751 +0x35e

**Comment by gao-feng** [comment]
golang bug on fedora
https://bugzilla.redhat.com/show_bug.cgi?id=1135152

**Comment by jstoja** [comment]
What's your version of hyper ? (`hyper version`)
Have you tried updating ?

**Comment by carmark** [comment]
@jstoja This is a known issue of golang on Redhat, you may check that above bug link.

**Comment by gnawux** [comment]
pull request #105 should fix this
